# source_url: https://gist.github.com/dreed47/b33a76472cc813f7bf48a63c3dde7dce
alias: Bambu Lab External Light Controller
description: Control additional lights based on printer status
mode: single

blueprint:
  name: Bambu Lab External Light Controller
  description: Control one or more lights based upon BambuLab X1C/P1S 3D printer
  domain: automation
  input:
    printer_online:
      name: Printer Online
      description: Select the printer online state binary sensor.
      selector:
        entity:
          filter:
            - domain:
                - binary_sensor
              integration: bambu_lab
          multiple: false
    printer_status:
      name: Printing Status
      description: Select the print status entity.
      selector:
        entity:
          filter:
            - domain:
                - sensor
              integration: bambu_lab
          multiple: false
    printer_stage:
      name: Print Stage
      description: Select the printer current stage entity.
      selector:
        entity:
          filter:
            - domain:
                - sensor
              integration: bambu_lab
          multiple: false
    printer_chamber_light:
      name: Internal Chamber Light
      description: Select the printer chamber light.
      selector:
        entity:
          filter:
            - domain:
                - light
              integration: bambu_lab
          multiple: false
    target_lights:
      name: Switched External Lights
      description: Select the lights you wish to control.
      selector:
        entity:
          filter:
            - domain:
                - light
          multiple: true

triggers:
  - alias: Trigger whenever printer stage, status, chamber light, or online state changes
    trigger: state
    entity_id:
      - !input printer_online
      - !input printer_status
      - !input printer_stage
      - !input printer_chamber_light

action:
  - delay: "00:00:05"
  - choose:
      - alias: Printer is offline, check again in 15secs and if so, turn lights off
        conditions:
            condition: state
            entity_id: !input printer_online
            state: "off"
        sequence:
          - delay: "00:00:15"
          - if:
              - alias: Printer offline after 15 seconds
                condition: state
                entity_id: !input printer_online
                state: "off"
                for: "00:00:10"
            then:
              - alias: Turn LED lights off, ignore chamber light
                action: light.turn_{{ printer_chamber_light.state }}
                target:
                  entity_id: !input target_lights
      - alias: LIDAR is not on, follow chamber light
        conditions:
            condition: not
            conditions:
              - condition: state
                entity_id: !input printer_stage
                state: scanning_bed_surface
                alias: Scanning Bed Surface
              - condition: state
                entity_id: !input printer_stage
                state: cleaning_nozzle_tip
                alias: Cleaning Nozzle Tip
              - condition: state
                entity_id: !input printer_stage
                state: calibrating_extrusion
                alias: Calibrating Extrusion
              - condition: state
                entity_id: !input printer_status
                state: offline
                alias: Printer is offline
        sequence:
          - alias: Turn LED lights off
            action: light.turn_off
            target:
              entity_id: !input target_lights
      - alias: Printer needs service, lights on, ignore chamber light
        conditions:
            condition: or
            conditions:
              - condition: state
                entity_id: !input printer_stage
                state: paused_filament_runout
              - condition: state
                entity_id: !input printer_stage
                state: paused_front_cover_falling
              - condition: state
                entity_id: !input printer_stage
                state: paused_nozzle_temperature_malfunction
              - condition: state
                entity_id: !input printer_stage
                state: paused_heat_bed_temperature_malfunction
              - condition: state
                entity_id: !input printer_stage
                state: paused_chamber_temperature_control_error
              - condition: state
                entity_id: !input printer_stage
                state: paused_cutter_error
              - condition: state
                entity_id: !input printer_stage
                state: paused_first_layer_error
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input target_lights
      - alias: Printer idle, lights follow chamber light
        conditions:
            condition: state
            entity_id: !input printer_stage
            state: idle
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input target_lights
      - alias: Printer printing, lights follow chamber light
        conditions:
            condition: state
            entity_id: !input printer_stage
            state: printing
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input target_lights
      - alias: AMS loading/unloading, lights follow chamber light
        conditions:
            condition: or
            conditions:
              - condition: state
                entity_id: !input printer_stage
                state: filament_unloading
              - condition: state
                entity_id: !input printer_stage
                state: filament_loading
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input target_lights
      - conditions:
          - alias: Printing finished, lights follow chamber light
            condition: state
            entity_id: !input printer_status
            state: finish
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input target_lights

      - alias: Printing paused, lights on, ignore chamber light
        conditions:
            condition: state
            entity_id: !input printer_status
            state: pause
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input target_lights
      - alias: Automatic Bed Leveling, lights follow chamber light
        conditions:
            condition: state
            entity_id: !input printer_stage
            state: auto_bed_leveling
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input target_lights
      - alias: Bed preheating, lights follow chamber light
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input printer_stage
                state: heatbed_preheating
              - condition: state
                entity_id: !input printer_stage
                state: Heating Hotend
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input target_lights
